# Generated by Django 3.2.25 on 2024-11-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_view', 'Can view MyModel'), ('can_create', 'Can create MyModel'), ('can_edit', 'Can edit MyModel'), ('can_delete', 'Can delete MyModel')],
            },
        ),
    ]
