from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet

# Router automatically generates URL routes for the ViewSets
router = DefaultRouter()
router.register(r'posts', PostViewSet)  # Register PostViewSet
router.register(r'comments', CommentViewSet)  # Register CommentViewSet

urlpatterns = [
    path('', include(router.urls)),  # Include all routes generated by the router
]
