from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet, FeedView, LikePostView, UnlikePostView

# Router automatically generates URL routes for the ViewSets
router = DefaultRouter()
router.register(r'posts', PostViewSet)  # Register PostViewSet
router.register(r'comments', CommentViewSet)  # Register CommentViewSet

urlpatterns = [
    path('', include(router.urls)),  # Include all routes generated by the router
    path('feed/', FeedView.as_view(), name='feed'),
    path('<int:pk>/like/', LikePostView.as_view(), name='like-post'),
    path('<int:pk>/unlike/', UnlikePostView.as_view(), name='unlike-post'),
]
